#!/usr/bin/env bash
### ABOUTME: See help text
set -euo pipefail

helptext="USAGE:     ${0##*/} ARG [ARG]
WTF:       ABOUTME
WHERE:     Conditions
DEFAULT:   Values
"

# shopt -s dotglob lastpipe  # add if as required

# functions go here
some_func(){
   declare -p FUNCNAME
}

# Detect whether this file is being sourced or executed.
if (return 0 2>/dev/null); then
   _sourced=true
else
   _sourced=false
fi

_main() {
   some_func
}

if ! $_sourced; then
   if [[ ${1:-} =~ ^--?h(elp)?$ ]]; then
      echo "$helptext" >&2
      exit
   fi
   _main "$@"
fi

unset _sourced
