#!/usr/bin/env bash

### ABOUTME: If the help text doesn't explain, put it here ###
helptext="USAGE:     ${0##*/} ARG [ARG]
WTF:       ABOUTME
WHERE:     Conditions
DEFAULT:   Values
"

# Detect whether this file is being sourced or executed.
if (return 0 2>/dev/null); then
   _sourced=true
else
   _sourced=false
fi

set -euo pipefail
IFS=$'\n\t'
# shopt -s dotglob lastpipe

# functions go here
some_func(){
   declare -p FUNCNAME
}

_main() {
   some_func
}

if ! $_sourced; then
   if [[ ${1:-} =~ ^--?h(elp)?$ ]]; then
      echo "$helptext" >&2
      exit
   fi
   _main "$@"
fi

unset _sourced
